include $(WEB_SERVER_BASE)/Makefiles/Makefile.Device
include $(WEB_SERVER_BASE)/Makefiles/Makefile.Widget
include $(WEB_SERVER_BASE)/Makefiles/Makefile.Layout
include $(WEB_SERVER_BASE)/Makefiles/Makefile.Ui